---
abstract: 'Enhancing Test::More for UTF8-based projects'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-More-UTF8
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
